baseURL = "https://bobstops.com/"
languageCode = "en-us"
title = "Bobs Tops and Upholstery"
theme = "hugo-arcana"
copyright = "Â© BobsTops. All rights reserved"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2
    [languages.es]
        languageName = "Spanish"
        weight = 3

[taxonomies]
    tag = "tags"

[params]
    description = "Award Winning Auto, Home, Marine, and Commercial Upholstery"
    images = ['images/metaimage.jpg']
    show_post_dates = false

    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"
    [[params.social]]
	title = "eBay"
	icon = "fa-ebay"
	url = "https://ebay.com/str/bobstopsandupholstery"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
