[[main]]
    name = "Dropdown"
    weight = 30
[[main]]
    parent = "Dropdown"
    name = "About"
    weight = 31
[[main]]
    parent = "Dropdown"
    name = "Services"
    weight = 32
[[main]]
    parent = "Dropdown"
    name = "Gallery"
    weight = 33
[[main]]
    parent = "Dropdown"
    name = "Submenu"
    weight = 34
[[main]]
    parent = "Submenu"
    name = "About"
    identifier = "about"
    weight = 35
[[main]]
    parent = "Submenu"
    name = "Team"
    weight = 36
[[main]]
    parent = "Submenu"
    name = "Awards"
    weight = 37
[[main]]
    parent = "Submenu"
    name = "Projects"
    weight = 38
[[main]]
    parent = "Submenu"
    name = "Veroeros feugiat"
    identifier = "sub-veroeros"
    weight = 39
[[main]]
    parent = "Dropdown"
    name = "Contact"
    weight = 40
[[main]]
    parent = "Dropdown"
    name = "Socials"
    weight = 41
